# Generated by Django 2.0.6 on 2018-06-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180614_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
