# Generated by Django 2.0.6 on 2018-06-14 10:30

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_kirrurl_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=256, validators=[shortener.validators.validate_url]),
        ),
    ]
